# Generated by Django 2.1.2 on 2018-11-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181101_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
