# Generated by Django 2.1.2 on 2018-11-04 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181104_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 20, 19, 41, 880598, tzinfo=utc)),
        ),
    ]
