# Generated by Django 2.1.2 on 2018-11-04 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181104_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 20, 19, 54, 110415, tzinfo=utc), verbose_name='date_joined'),
        ),
    ]
