# Generated by Django 2.1.2 on 2018-11-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181104_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='card_validity',
        ),
    ]
