# Generated by Django 2.1.2 on 2018-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181104_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FilePathField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('FANTASY', 'Fantasy'), ('HISTORY', 'History'), ('MYSTERY', 'Mystery'), ('ROMANCE', 'Romance'), ('SCIENCE FICTION', 'Science fiction'), ('THRILLER', 'Thriller')], default='', max_length=20),
        ),
    ]
